export const drawDetailsResult = {
  data: {
    draw: {
      draws: [
        {
          additionalNumbers: ["7", "10"],
          date: "Feb 09 2024",
          gameAmount: "5128195400",
          jackpot: "62000000",
          megaPlier: "",
          numbers: ["4", "10", "11", "20", "22"],
          odds: [
            {
              description: "5 Richtige + 2 Eurozahlen",
              descriptionShort: "5 + 2 EZ",
              link: "",
              numberOfWinners: "1",
              numbers: [],
              odd: "6325993870",
              winningClass: 1,
              withOptions: [],
              __typename: "modelOdd",
            },
            {
              description: "5 Richtige + 1 Eurozahl",
              descriptionShort: "5 + 1 EZ",
              link: "",
              numberOfWinners: "10",
              numbers: [],
              odd: "22051240",
              winningClass: 2,
              withOptions: [],
              __typename: "modelOdd",
            },
            {
              description: "5 Richtige",
              descriptionShort: "5",
              link: "",
              numberOfWinners: "11",
              numbers: [],
              odd: "11305330",
              winningClass: 3,
              withOptions: [],
              __typename: "modelOdd",
            },
            {
              description: "4 Richtige + 2 Eurozahlen",
              descriptionShort: "4 + 2 EZ",
              link: "",
              numberOfWinners: "59",
              numbers: [],
              odd: "347670",
              winningClass: 4,
              withOptions: [],
              __typename: "modelOdd",
            },
            {
              description: "4 Richtige + 1 Eurozahl",
              descriptionShort: "4 + 1 EZ",
              link: "",
              numberOfWinners: "1359",
              numbers: [],
              odd: "18860",
              winningClass: 5,
              withOptions: [],
              __typename: "modelOdd",
            },
            {
              description: "3 Richtige + 2 Eurozahlen",
              descriptionShort: "3 + 2 EZ",
              link: "",
              numberOfWinners: "2134",
              numbers: [],
              odd: "13210",
              winningClass: 6,
              withOptions: [],
              __typename: "modelOdd",
            },
            {
              description: "4 Richtige",
              descriptionShort: "4",
              link: "",
              numberOfWinners: "2561",
              numbers: [],
              odd: "8000",
              winningClass: 7,
              withOptions: [],
              __typename: "modelOdd",
            },
            {
              description: "2 Richtige + 2 Eurozahlen",
              descriptionShort: "2 + 2 EZ",
              link: "",
              numberOfWinners: "27283",
              numbers: [],
              odd: "2390",
              winningClass: 8,
              withOptions: [],
              __typename: "modelOdd",
            },
            {
              description: "3 Richtige + 1 Eurozahl",
              descriptionShort: "3 + 1 EZ",
              link: "",
              numberOfWinners: "45825",
              numbers: [],
              odd: "1590",
              winningClass: 9,
              withOptions: [],
              __typename: "modelOdd",
            },
            {
              description: "3 Richtige",
              descriptionShort: "3",
              link: "",
              numberOfWinners: "96470",
              numbers: [],
              odd: "1430",
              winningClass: 10,
              withOptions: [],
              __typename: "modelOdd",
            },
            {
              description: "1 Richtige + 2 Eurozahlen",
              descriptionShort: "1 + 2 EZ",
              link: "",
              numberOfWinners: "135575",
              numbers: [],
              odd: "1270",
              winningClass: 11,
              withOptions: [],
              __typename: "modelOdd",
            },
            {
              description: "2 Richtige + 1 Eurozahl",
              descriptionShort: "2 + 1 EZ",
              link: "",
              numberOfWinners: "582636",
              numbers: [],
              odd: "890",
              winningClass: 12,
              withOptions: [],
              __typename: "modelOdd",
            },
          ],
          powerPlay: "",
          shares: [],
          time: "",
          __typename: "modelDraw",
        },
      ],
      __typename: "draw",
    },
  },
};

export const drawsResult = {
  data: {
    draw: {
      draws: [
        {
          date: "Feb 09 2024",
          additionalNumbers: ["7", "10"],
          numbers: ["4", "10", "11", "20", "22"],
          __typename: "modelDraw",
        },
        {
          date: "Feb 06 2024",
          additionalNumbers: ["1", "4"],
          numbers: ["16", "19", "20", "26", "44"],
          __typename: "modelDraw",
        },
        {
          date: "Feb 02 2024",
          additionalNumbers: ["8", "11"],
          numbers: ["13", "17", "21", "30", "39"],
          __typename: "modelDraw",
        },
        {
          date: "Jan 30 2024",
          additionalNumbers: ["9", "11"],
          numbers: ["10", "12", "15", "46", "48"],
          __typename: "modelDraw",
        },
        {
          date: "Jan 26 2024",
          additionalNumbers: ["6", "7"],
          numbers: ["18", "23", "35", "37", "41"],
          __typename: "modelDraw",
        },
        {
          date: "Jan 23 2024",
          additionalNumbers: ["5", "8"],
          numbers: ["9", "18", "20", "32", "39"],
          __typename: "modelDraw",
        },
        {
          date: "Jan 19 2024",
          additionalNumbers: ["7", "10"],
          numbers: ["10", "12", "18", "33", "47"],
          __typename: "modelDraw",
        },
        {
          date: "Jan 16 2024",
          additionalNumbers: ["4", "9"],
          numbers: ["6", "19", "32", "39", "42"],
          __typename: "modelDraw",
        },
        {
          date: "Jan 12 2024",
          additionalNumbers: ["6", "9"],
          numbers: ["3", "31", "34", "43", "45"],
          __typename: "modelDraw",
        },
        {
          date: "Jan 09 2024",
          additionalNumbers: ["7", "10"],
          numbers: ["9", "12", "26", "41", "47"],
          __typename: "modelDraw",
        },
      ],
      __typename: "draw",
    },
  },
};
